services:
    _defaults:
        public: true

    CoreShop\Bundle\IndexBundle\Command\IndexCommand:
        arguments:
          - '@coreshop.repository.index'
          - '@coreshop.index.updater'
          - '@event_dispatcher'
        tags:
          - { name: console.command, command: coreshop:index }
