services:
    coreshop.registry.index.condition.renderers:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Component\Index\Condition\DynamicRendererInterface
            - condition-renderers

    ## Renderer
    coreshop.index.condition.renderer: '@CoreShop\Component\Index\Condition\ConditionRenderer'
    CoreShop\Component\Index\Condition\ConditionRendererInterface: '@CoreShop\Component\Index\Condition\ConditionRenderer'
    CoreShop\Component\Index\Condition\ConditionRenderer:
        arguments:
            - '@coreshop.registry.index.condition.renderers'

    coreshop.index.condition.renderer.mysql.abstract: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer:
        abstract: true
        arguments:
            - '@doctrine.dbal.default_connection'

    coreshop.index.condition.renderer.mysql.compare: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\CompareRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\CompareRenderer:
        parent: CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer
        tags:
            - { name: coreshop.index.condition.renderer, type: mysql_compare }

    coreshop.index.condition.renderer.mysql.concat: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\ConcatRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\ConcatRenderer:
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@CoreShop\Component\Index\Condition\ConditionRendererInterface'
        tags:
            - { name: coreshop.index.condition.renderer, type: mysql_concat }

    coreshop.index.condition.renderer.mysql.in: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\InRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\InRenderer:
        parent: CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer
        tags:
            - { name: coreshop.index.condition.renderer, type: mysql_in }

    coreshop.index.condition.renderer.mysql.is_null: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\IsNullRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\IsNullRenderer:
        parent: CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer
        tags:
            - { name: coreshop.index.condition.renderer, type: mysql_is_null }

    coreshop.index.condition.renderer.mysql.is: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\IsRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\IsRenderer:
        parent: CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer
        tags:
            - { name: coreshop.index.condition.renderer, type: mysql_is }

    coreshop.index.condition.renderer.mysql.like: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\LikeRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\LikeRenderer:
        parent: CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer
        tags:
            - { name: coreshop.index.condition.renderer, type: mysql_like }

    coreshop.index.condition.renderer.mysql.range: '@CoreShop\Bundle\IndexBundle\Condition\Mysql\RangeRenderer'
    CoreShop\Bundle\IndexBundle\Condition\Mysql\RangeRenderer:
        parent: CoreShop\Bundle\IndexBundle\Condition\Mysql\AbstractMysqlDynamicRenderer
        tags:
            - { name: coreshop.index.condition.renderer, type: mysql_range }
