services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CoreShop\Bundle\IndexBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('CoreShopIndexBundle')"
