services:
    coreshop.registry.index.order.renderers:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Component\Index\Order\DynamicOrderRendererInterface
            - order-renderers

    ## Renderer
    coreshop.index.order.renderer: '@CoreShop\Component\Index\Order\OrderRenderer'
    CoreShop\Component\Index\Order\OrderRendererInterface: '@CoreShop\Component\Index\Order\OrderRenderer'
    CoreShop\Component\Index\Order\OrderRenderer:
        arguments:
            - '@coreshop.registry.index.order.renderers'

    coreshop.index.order.renderer.mysql.abstract: '@CoreShop\Bundle\IndexBundle\Order\Mysql\AbstractMysqlDynamicRenderer'
    CoreShop\Bundle\IndexBundle\Order\Mysql\AbstractMysqlDynamicRenderer:
        abstract: true
        arguments:
            - '@doctrine.dbal.default_connection'

    coreshop.index.order.renderer.mysql.simple: '@CoreShop\Bundle\IndexBundle\Order\Mysql\SimpleOrderRenderer'
    CoreShop\Bundle\IndexBundle\Order\Mysql\SimpleOrderRenderer:
        parent: CoreShop\Bundle\IndexBundle\Order\Mysql\AbstractMysqlDynamicRenderer
        tags:
            - { name: coreshop.index.order.renderer, type: mysql_simple }

